server {
    listen 80;
    listen [::]:80;

    server_name dynamicinitiative.online www.dynamicinitiative.online;

    # Redirect all HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name dynamicinitiative.online www.dynamicinitiative.online;

    root /var/www/html;
    index index.html;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/dynamicinitiative.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dynamicinitiative.online/privkey.pem;

    # Homepage
    location / {
        try_files $uri $uri/ =404;
    }

    # API Endpoint
    location /api {
        default_type application/json;
        return 200 '{"message":"HNGI14 Stage 1","track":"DevOps","username":"Dynamic_D"}';
    }
}
